version: "3.11"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  redis:
    image: redis
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A library_team_project worker --loglevel=info
    volumes:
      - ./:/app
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A library_team_project flower
    volumes:
      - ./:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  celery_beat:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             celery -A library_team_project beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - app
