# Generated by Django 4.2.6 on 2023-10-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "PENDING"), (1, "PAID")], default=0
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "PAYMENT"), (1, "FINE")], default=0
                    ),
                ),
                ("session_url", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=63)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
